### ISSUE TITLE
Main class not found dependecies

### ISSUE THREAD

**Issue by ricardocunha** [le-moulin-studio/java-semantic-diff#4]
Main class not found the dependecies:

import com.lemoulinstudio.sdiff.parser.java.JavaLexer;
import com.lemoulinstudio.sdiff.parser.java.JavaParser;

**Comment by myyychal** [comment]
Is there a possibility that you will add this two classes to the repo?

**Comment by green-coder** [comment]
Hi, the project was a short experiment which never reached the level where it is functional. The best contribution was done in the documentation instead of the program. At the moment, the project is dead, adding the 2 classes would be meaningless.

**Comment by myyychal** [comment]
Mhmm, I get it, it's too bad :(
But is there a possibility that you can send me this two classes?
It would be very helpful for me, because I am working on a project that has some similarities.

**Comment by green-coder** [comment]
Could you point me this project ? Is it on Github ?

**Comment by myyychal** [comment]
Well, not yet ;)
It is still at the conceptual stage.
It is a student project and so far I have looked at SemanticMerge and their conceptions.

**Comment by green-coder** [comment]
I committed badbd873e0d5df585bd63c316f2a72c75d013796 which should fix the problem, please let me know if it works for you.
